version: '3.3'
services:
    app:
      build: ./
      container_name: app
      command: bash -c ". venv/bin/activate
              && python app.py"
      environment:
        - DB_URL=sqlite:///testDB.db
      restart: always
      ports:
        - 8050:8050